import {
  DEFAULT_PRIORITY,
  type ApiBanner,
  type ApiCharacter,
  type Banner,
  type Character,
} from "./types";

export const GENSHIN_CHARACTERS = [
  "albedo",
  "alhaitham",
  "aloy",
  "amber",
  "itto",
  "arlecchino",
  "baizhu",
  "barbara",
  "beidou",
  "bennett",
  "candace",
  "charlotte",
  "chasca",
  "chevreuse",
  "chiori",
  "chongyun",
  "citlali",
  "clorinde",
  "collei",
  "cyno",
  "dehya",
  "diluc",
  "diona",
  "dori",
  "emilie",
  "escoffier",
  "eula",
  "faruzan",
  "fischl",
  "freminet",
  "furina",
  "gaming",
  "ganyu",
  "gorou",
  "hu tao",
  "iansan",
  "jean",
  "kachina",
  "kazuha",
  "kaeya",
  "ayaka",
  "ayato",
  "kaveh",
  "keqing",
  "kinich",
  "kirara",
  "klee",
  "kujou sara",
  "kuki shinobu",
  "lan yan",
  "layla",
  "lisa",
  "lynette",
  "lyney",
  "mavuika",
  "mika",
  "mona",
  "mualani",
  "nahida",
  "navia",
  "neuvillette",
  "nilou",
  "ningguang",
  "noelle",
  "ororon",
  "qiqi",
  "raiden",
  "razor",
  "rosaria",
  "kokomi",
  "sayu",
  "sethos",
  "shenhe",
  "heizou",
  "sigewinne",
  "skirk",
  "sucrose",
  "tartaglia",
  "thoma",
  "tighnari",
  "traveler",
  "varesa",
  "venti",
  "wanderer",
  "wriothesley",
  "xiangling",
  "xianyun",
  "xiao",
  "xilonen",
  "xingqiu",
  "xinyan",
  "yae miko",
  "yanfei",
  "yaoyao",
  "yelan",
  "yoimiya",
  "mizuki",
  "yun jin",
  "zhongli",
] as const;

// API Data (simulating data that would come from an external API)
// --------------------------------------------------------------

// API Character data
export const API_CHARACTERS: Record<string, ApiCharacter> = {
  Escoffier: {
    id: "escoffier",
    name: "Escoffier",
    rarity: 5,
    element: "Cryo",
    weaponType: "Sword",
  },
  Navia: {
    id: "navia",
    name: "Navia",
    rarity: 5,
    element: "Geo",
    weaponType: "Claymore",
  },
  Kinich: {
    id: "kinich",
    name: "Kinich",
    rarity: 5,
    element: "Dendro",
    weaponType: "Claymore",
  },
  Raiden: {
    id: "raiden",
    name: "Raiden",
    rarity: 5,
    element: "Electro",
    weaponType: "Polearm",
  },
  Skirk: {
    id: "skirk",
    name: "Skirk",
    rarity: 5,
    element: "Cryo",
    weaponType: "Sword",
  },
  Mavuika: {
    id: "mavuika",
    name: "Mavuika",
    rarity: 5,
    element: "Pyro",
    weaponType: "Claymore",
  },
  Emilie: {
    id: "emilie",
    name: "Emilie",
    rarity: 5,
    element: "Dendro",
    weaponType: "Sword",
  },
  Shenhe: {
    id: "shenhe",
    name: "Shenhe",
    rarity: 5,
    element: "Cryo",
    weaponType: "Polearm",
  },
};

// API Banner data
export const API_BANNERS: ApiBanner[] = [
  {
    id: "5.6v1",
    version: "5.6v1",
    name: "5.6v1",
    startDate: "2024-05-01",
    endDate: "2024-05-15",
    characters: [API_CHARACTERS.Escoffier, API_CHARACTERS.Navia],
  },
  {
    id: "5.6v2",
    version: "5.6v2",
    name: "5.6v2",
    startDate: "2024-05-16",
    endDate: "2024-05-30",
    characters: [API_CHARACTERS.Kinich, API_CHARACTERS.Raiden],
  },
  {
    id: "5.7v1",
    version: "5.7v1",
    name: "5.7v1",
    startDate: "2024-06-01",
    endDate: "2024-06-15",
    characters: [API_CHARACTERS.Skirk, API_CHARACTERS.Shenhe],
  },
  {
    id: "5.7v2",
    version: "5.7v2",
    name: "5.7v2",
    startDate: "2024-06-16",
    endDate: "2024-06-30",
    characters: [API_CHARACTERS.Mavuika, API_CHARACTERS.Emilie],
  },
];

// Helper function to convert API data to application state
// -------------------------------------------------------

// Convert API character to application Character with state
export const apiCharacterToCharacter = (apiChar: ApiCharacter): Character => ({
  ...apiChar,
  wishesToSpend: 0,
  priority: DEFAULT_PRIORITY,
  maxConst: 0,
});

// Convert API banner to application Banner with state
export const apiBannerToBanner = (apiBanner: ApiBanner): Banner => ({
  ...apiBanner,
  characters: apiBanner.characters.map(apiCharacterToCharacter),
});

// Initial banners with application state for new users
export const initialBanners: Banner[] = API_BANNERS.map(apiBannerToBanner);
