name: Run Tests (Blacksmith)

on:
  # Run tests on every push to main/master
  push:
    branches: [main, master]

  # Run tests on all pull requests
  pull_request:
    branches: [main, master]

  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  jest-shard:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    name: Jest test ${{ matrix.chunk }}

    strategy:
      fail-fast: true
      matrix:
        chunk: [1, 2, 3, 4, 5, 6, 7, 8]

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Set up Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 18.12.1
          cache: pnpm

      - name: Install package.json dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Test with Jest
        run: npm jest --shard=${{ matrix.chunk }}/8 --maxWorkers=2 --silent
